spring:
 cloud:
  gateway:
   routes:
     - id: servicios-productos
       uri: lb://servicio-productos
       predicates:
         - Path=/api/productos/**
       filters:
        - StripPrefix=2
     - id: servicios-productos
       uri: lb://servicio-items
       predicates:
         - Path=/api/items/**
       filters:
         - StripPrefix=2
     - id: servicios-productos
       uri: lb://servicio-saludo
       predicates:
         - Path=/api/saludo/**
       filters:
         - StripPrefix=2